@startuml
skinparam classAttributeIconSize 0
skinparam classFontSize 13
skinparam classBackgroundColor #EAF3DE
skinparam classBorderColor #3B6D11

enum EstadoNivel {
  BLOQUEADO
  EN_PROGRESO
  COMPLETADO
}

abstract class Usuario {
  # id: int
  # nombre: String
  # email: String
  # contrasena: String
  + iniciarSesion(): void
  + cerrarSesion(): void
}

class Invitado {
  + verContenido(): void
  + jugarRetoTemporal(): void
  + registrarse(): void
}

class Alumno {
  - xpTotal: int
  - nivelRango: int
  - tokensTotales: int
  + jugarRetoConGuardado(reto: Reto): void
  + editarPerfil(): void
  + verProgreso(): void
  + consultarRanking(): void
  + canjearTokens(recompensa: Recompensa): void
  + ganarXP(puntos: int): void
}

class Profesor {
  + crearReto(nivel: Nivel): Reto
  + crearEquipo(nombre: String): Equipo
  + asignarReto(equipo: Equipo, reto: Reto): void
  + verProgresoAlumnos(equipo: Equipo): void
}

class Administrador {
  + crearJuego(juego: Juego): void
  + eliminarJuego(juego: Juego): void
  + crearNivel(nivel: Nivel): void
  + gestionarUsuarios(): void
  + moderarRanking(): void
  + validarCanje(canje: Canje): void
}

class Juego {
  - id: int
  - titulo: String
  - lenguaje: String
  - dificultad: String
  - activo: boolean
  + agregarNivel(nivel: Nivel): void
  + getNiveles(): List~Nivel~
}

class Nivel {
  - id: int
  - titulo: String
  - orden: int
  - xpRecompensa: int
  - estadoNivel: EstadoNivel
  + iniciar(): void
  + finalizar(): void
  + getRetos(): List~Reto~
}

class Reto {
  - id: int
  - enunciado: String
  - tipo: String
  - solucion: String
  + validarRespuesta(respuesta: String): boolean
}

class Recompensa {
  - id: int
  - nombre: String
  - costeTokens: int
  - tipo: String
  - activo: boolean
}

class Canje {
  - id: int
  - fechaSolicitud: Date
  - estado: String
  + validar(): void
  + rechazar(): void
}

class Equipo {
  - id: int
  - nombre: String
  + agregarAlumno(alumno: Alumno): void
  + quitarAlumno(alumno: Alumno): void
  + getAlumnos(): List~Alumno~
}

' ── HERENCIA ──

Alumno -down-|> Invitado
Invitado -down-|> Usuario
Profesor -down-|> Alumno
Administrador -left-|> Usuario

' ── RELACIONES ──
Juego "1" *-- "1..*" Nivel : contiene
Nivel "1" *-- "1..*" Reto : incluye
Nivel -- EstadoNivel : usa
Alumno "0..*" -right- "0..*" Reto : juega
Alumno "1" -- "0..*" Canje : solicita
Recompensa "1" -- "0..*" Canje : en
Administrador "1" -- "0..*" Canje : valida
Administrador "1" -- "0..*" Juego : gestiona
Profesor "1" *-- "0..*" Equipo : gestiona
Equipo "0..*" o-- "0..*" Alumno : agrupa

@enduml